apiVersion: v1
kind: Namespace
metadata:
  name: org1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: org1admin
  namespace: org1
---
apiVersion: v1
kind: Secret
metadata:
  name: org1admin-secret
  namespace: org1
  annotations:
    kubernetes.io/service-account.name: org1admin
type: kubernetes.io/service-account-token
---
apiVersion: ibp.com/v1beta1
kind: IBPCA
metadata:
  name: org1-ca
  namespace: org1
spec:
  action:
    renew: {}
  configoverride:
    ca:
      registry:
        identities:
          - name: rcaadmin
            pass: rcaadminpw
            type: client
            attrs:
              hf.Registrar.Roles: "*"
              hf.Registrar.DelegateRoles: "*"
              hf.Revoker: true
              hf.IntermediateCA: true
              hf.GenCRL: true
              hf.Registrar.Attributes: "*"
              hf.AffiliationMgr: true
          - name: org1admin
            pass: org1adminpw
            type: admin
      debug: true
      signing:
        default:
          expiry: 87600h0m0s
    tlsca:
      registry:
        identities:
          - name: admin
            pass: adminpw
            type: client # todo: shouldn't this be an admin?
            attrs:
              hf.Registrar.Roles: "*"
              hf.Registrar.DelegateRoles: "*"
              hf.Revoker: true
              hf.IntermediateCA: true
              hf.GenCRL: true
              hf.Registrar.Attributes: "*"
              hf.AffiliationMgr: true
          - name: org1admin
            pass: org1adminpw
            type: admin
      debug: true
      signing:
        default:
          expiry: 87600h0m0s
  customNames:
    pvc: {}
  domain: localho.st
  images:
    caImage: hyperledgerk8s/fabric-ca
    caTag: "1.5.5"
    caInitImage: hyperledgerk8s/ubi-minimal
    caInitTag: latest
  license:
    accept: true
  replicas: 1
  resources:
    ca:
      limits:
        cpu: 100m
        memory: 200M
      requests:
        cpu: 10m
        memory: 10M
    init:
      limits:
        cpu: 100m
        memory: 200M
      requests:
        cpu: 10m
        memory: 10M
  service:
    type: ClusterIP
  storage:
    ca:
      class: "standard"
      size: 100M
  version: "1.5"
---
apiVersion: v1
kind: Secret
metadata:
  name: org1-admin-secret
  namespace: org1
data:
  enrollSecret: b3JnMWFkbWlucHcK
---
apiVersion: ibp.com/v1beta1
kind: Organization
metadata:
  name: org1
  namespace: org1
spec:
  license:
    accept: true
  displayName: "test organization"
  admin: org1admin
  adminSecret: org1-admin-secret
  caReference: 
    name: org1-ca
    ca: ca
  description: "test org1"
