apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-cluster-role
rules:
# CRD Proposal
- apiGroups:
    - ibp.com
  resources:
    - proposals
  verbs:
    - create
    - get
    - list
    - watch
- apiGroups:
    - ibp.com
  resources:
    - proposals/status
  verbs:
    - get